#!/usr/bin/env bash
set -euo pipefail

PORT_STORE="/etc/tunnel/user_ports.json"
NGINX_USERS_DIR="/etc/nginx/conf.d"
NGINX_USERS_CONF="$NGINX_USERS_DIR/subname_registrar_locations.conf"
LOCK="/var/lock/regen_nginx_routes.lock"

mkdir -p "$NGINX_USERS_DIR" /var/lock
exec 9>"$LOCK"
flock 9

# Build list of desired files
DESIRED_DIR="$(mktemp -d)"
trap 'rm -rf "$DESIRED_DIR"; flock -u 9' EXIT
DESIRED_CONFIG="$DESIRED_DIR/subname_registrar_locations.conf"

if [ ! -f "$PORT_STORE" ]; then
  printf '%s\n' '{"users": {}, "port_range": {"min": 9001, "max": 9100}}' > "$PORT_STORE"
  chmod 600 "$PORT_STORE"
  chown root:root "$PORT_STORE"
fi

python3 - "$PORT_STORE" "$DESIRED_CONFIG" <<'PY'
import json
import re
import sys

store, out = sys.argv[1:]
with open(store, encoding="utf-8") as f:
    data = json.load(f)

users = data.get("users", {})

lines = [
    "# AUTO-GENERATED by regen_nginx_routes.sh. DO NOT EDIT.",
    "",
]

for user, port in sorted(users.items()):
    if not re.fullmatch(r"[A-Za-z0-9_-]+", user):
        raise SystemExit(f"Invalid user name: {user!r}")
    if not isinstance(port, int) or not (1 <= port <= 65535):
        raise SystemExit(f"Invalid port for {user!r}: {port!r}")

    lines.extend([
        f"# User: {user} -> 127.0.0.1:{port}",
        f"location = /{user} {{",
        f"    return 301 /{user}/;",
        "}",
        "",
        f"location ^~ /{user}/ {{",
        f"    proxy_pass http://127.0.0.1:{port}/;",
        "    include /etc/nginx/snippets/bitone_proxy.conf;",
        "}",
        "",
    ])

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
PY

# Replace the single generated include atomically.
install -m 640 "$DESIRED_CONFIG" "$NGINX_USERS_CONF"

# The parent DOMAIN server configuration was resolved and installed at
# installation time. Runtime route regeneration only changes this include file.
BACKUP_CONFIG="${NGINX_USERS_CONF}.bak"

if [ -f "$NGINX_USERS_CONF" ]; then
    cp -a "$NGINX_USERS_CONF" "$BACKUP_CONFIG"
fi

install -m 640 "$DESIRED_CONFIG" "$NGINX_USERS_CONF"

if nginx -t; then
    systemctl reload nginx
    rm -f "$BACKUP_CONFIG"
else
    if [ -f "$BACKUP_CONFIG" ]; then
        mv -f "$BACKUP_CONFIG" "$NGINX_USERS_CONF"
    else
        rm -f "$NGINX_USERS_CONF"
    fi
    exit 3
fi

