#!/usr/bin/env bash
set -euo pipefail
: "${DOMAIN:?DOMAIN must be set before regen_nginx_routes.sh}"

PORT_STORE="/etc/tunnel/user_ports.json"
NGINX_DIR="/etc/nginx/conf.d"
LOCK="/var/lock/regen_nginx_routes.lock"
WEB_ROOT="/var/www/${DOMAIN}"

mkdir -p "$NGINX_DIR" "$WEB_ROOT" /var/lock
exec 9>"$LOCK"
flock 9

# Build list of desired files
DESIRED_DIR="$(mktemp -d)"
trap 'rm -rf "$DESIRED_DIR"; flock -u 9' EXIT
DESIRED_CONFIG="$DESIRED_DIR/${DOMAIN}.conf"

[ -f "$PORT_STORE" ] || printf '{"users":{}}\n' > "$PORT_STORE"

python3 - "$PORT_STORE" "$DESIRED_CONFIG" "$DOMAIN" "$WEB_ROOT" <<'PY'
import json,re,sys
store,out,domain,webroot=sys.argv[1:]
data=json.load(open(store,encoding="utf-8"))
users=data.get("users",{})
if not re.fullmatch(r"[A-Za-z0-9.-]+",domain):
    raise SystemExit("Invalid DOMAIN")
lines=[
"# AUTO-GENERATED by subname_registrar. DO NOT EDIT.",
"server {",
"    listen 127.0.0.1:8080;",
f"    server_name {domain};",
f"    root {webroot};",
"    index index.html index.htm;",
"",
"    location / {",
"        try_files $uri $uri/ =404;",
"    }",""]
for user,port in sorted(users.items()):
    if not re.fullmatch(r"[A-Za-z0-9_-]+",user):
        raise SystemExit(f"Invalid user: {user}")
    if not isinstance(port,int): raise SystemExit(f"Invalid port: {user}")
    lines += [
        f"    location = /{user} {{",
        f"        return 301 /{user}/;",
        "    }","",
        f"    location ^~ /{user}/ {{",
        f"        proxy_pass http://127.0.0.1:{port}/;",
        "        include /etc/nginx/snippets/bitone_proxy.conf;",
        "    }",""]
lines += ["}",""]
open(out,"w",encoding="utf-8").write("\n".join(lines))
PY

# Validate before replacing the live generated configuration.
install -m 640 "$DESIRED_CONFIG" "$NGINX_DIR/${DOMAIN}.conf"
nginx -t
systemctl reload nginx
